// <auto-generated />
using System;
using Foundation.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foundation.Web.Migrations
{
    [DbContext(typeof(ScaleDbContext))]
    [Migration("20260911183649_AddCardSurfaceGates")]
    partial class AddCardSurfaceGates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Foundation.Web.Models.AppSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowCardDesktop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowCardKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowCardMobile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowSkipBin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowSkipCarrier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowSkipCommodity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowSkipCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowSkipDestination")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowSkipLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowSkipTruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowTareResetCard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowTareResetKiosk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowTareResetMobile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiDefinitionPin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoClearStaleRetainedTare")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BinCommodityLock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BinRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultReportUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DemoMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSpanish")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOrderBin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOrderCarrier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOrderCommodity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOrderCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOrderDestination")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOrderLocation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOrderNotes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldOrderTruckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header3")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Header4")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HideCarrier")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideCommodity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideDestination")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideKioskOnScreenButtons")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideLocation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideNotes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideTruckId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("BLOB");

                    b.Property<string>("IconContentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InboundCameraId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InboundPrinterId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KioskCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("KioskCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KioskDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KioskPrinterId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("MobileRangeMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(50);

                    b.Property<bool>("MobileRequireLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("OutboundCameraId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutboundPrinterId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrintSignatureOnTicket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PromptKioskBinOnInbound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskBinOnOutbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromptKioskCarrier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskCommodityOnInbound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskCommodityOnOutbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromptKioskCustomerOnInbound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskCustomerOnOutbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromptKioskDestinationOnInbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromptKioskDestinationOnOutbound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskLocationOnInbound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PromptKioskLocationOnOutbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromptKioskTruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("RecallLastValues")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RecycleCards")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemotePrintMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SavePicture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScaleId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignaturePadId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SignatureRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsPerPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseBinInventory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseCardReader")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseLiveView")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseLogin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseQuickBooks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseRetainedTare")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSetup", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowCardDesktop = true,
                            AllowCardKiosk = true,
                            AllowCardMobile = true,
                            AllowSkipBin = true,
                            AllowSkipCarrier = true,
                            AllowSkipCommodity = true,
                            AllowSkipCustomer = true,
                            AllowSkipDestination = true,
                            AllowSkipLocation = true,
                            AllowSkipTruckId = true,
                            AllowTareResetCard = true,
                            AllowTareResetKiosk = true,
                            AllowTareResetMobile = true,
                            ApiDefinitionPin = "12345",
                            AutoClearStaleRetainedTare = true,
                            BinCommodityLock = false,
                            BinRequired = false,
                            DefaultReportUnit = "lbs",
                            DemoMode = false,
                            EnableSpanish = false,
                            FieldOrderBin = 65,
                            FieldOrderCarrier = 30,
                            FieldOrderCommodity = 10,
                            FieldOrderCustomer = 20,
                            FieldOrderDestination = 60,
                            FieldOrderLocation = 50,
                            FieldOrderNotes = 70,
                            FieldOrderTruckId = 40,
                            Header1 = "Foundation",
                            Header2 = "",
                            Header3 = "",
                            Header4 = "",
                            HideCarrier = false,
                            HideCommodity = false,
                            HideCustomer = false,
                            HideDestination = false,
                            HideKioskOnScreenButtons = false,
                            HideLocation = false,
                            HideNotes = false,
                            HideTruckId = false,
                            KioskCode = "12345",
                            KioskCount = 0,
                            KioskDarkMode = true,
                            Language = "en",
                            MobileRangeMeters = 50,
                            MobileRequireLocation = true,
                            PrintSignatureOnTicket = true,
                            PromptKioskBinOnInbound = true,
                            PromptKioskBinOnOutbound = false,
                            PromptKioskCarrier = true,
                            PromptKioskCommodityOnInbound = true,
                            PromptKioskCommodityOnOutbound = false,
                            PromptKioskCustomerOnInbound = true,
                            PromptKioskCustomerOnOutbound = false,
                            PromptKioskDestinationOnInbound = false,
                            PromptKioskDestinationOnOutbound = true,
                            PromptKioskLocationOnInbound = true,
                            PromptKioskLocationOnOutbound = false,
                            PromptKioskTruckId = true,
                            RecallLastValues = false,
                            RecycleCards = false,
                            RemotePrintMode = "None",
                            SavePicture = false,
                            SignatureMode = "None",
                            SignatureRequired = false,
                            Theme = "default",
                            TicketNumber = 1,
                            TicketsPerPage = 1,
                            TimeZoneId = "America/Chicago",
                            UseBinInventory = false,
                            UseCardReader = false,
                            UseLiveView = false,
                            UseLogin = false,
                            UseQuickBooks = false,
                            UseRetainedTare = false
                        });
                });

            modelBuilder.Entity("Foundation.Web.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Bin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BinName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("BinName")
                        .IsUnique();

                    b.ToTable("Bins", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.BinAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountLbs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Bin");

                    b.ToTable("BinAdjustments", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.CameraConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraBrand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraPassword")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraUser")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LiveViewEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RtspUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsbCommand")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsbDeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId")
                        .IsUnique();

                    b.ToTable("CameraConfigs", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bin")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("Issued")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTicket")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenTicket")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecycleMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Default");

                    b.Property<string>("TruckId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("OpenTicket");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.CardCustomValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("CardId", "CustomFieldId")
                        .IsUnique();

                    b.ToTable("CardCustomValues", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CarrierName")
                        .IsUnique();

                    b.ToTable("Carriers", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Commodity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommodityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double?>("UnitPounds")
                        .HasColumnType("REAL");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CommodityName")
                        .IsUnique();

                    b.ToTable("Commodities", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.CustomField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ListValues")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentField")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Precision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PromptAtKiosk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOnTicket")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomFields", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.CustomFieldListValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId", "ParentValue", "Value")
                        .IsUnique();

                    b.ToTable("CustomFieldListValues", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("CustomerName")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("DestinationName")
                        .IsUnique();

                    b.ToTable("Destinations", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSendUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordProtected")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = false,
                            Host = "mail.smtp2go.com",
                            Port = 2525,
                            SecurityMode = "StartTls"
                        });
                });

            modelBuilder.Entity("Foundation.Web.Models.Kiosk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReaderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScaleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Kiosks", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.LoadEmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.HasIndex("Ticket", "RuleId")
                        .IsUnique();

                    b.ToTable("LoadEmailLogs", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.LoadEmailRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommodityFilter")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFilter")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectTemplate")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LoadEmailRules", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("LocationName")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.ReportSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cc")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommodityFilter")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerFilter")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GroupCommoditiesIntoSheets")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeGrossTare")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SendHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SendMinute")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendWhenEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectTemplate")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReportSchedules", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.ReportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReportTemplates", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Scale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GateId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HardwareId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InboundPrinterId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutboundPrinterId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Scales", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Transaction", b =>
                {
                    b.Property<string>("Ticket")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bin")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commodity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InScale")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("InWeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualInbound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualOutbound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutScale")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutWeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SentToQuickBooks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransferToBin")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TruckId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Void")
                        .HasColumnType("INTEGER");

                    b.HasKey("Ticket");

                    b.HasIndex("Carrier");

                    b.HasIndex("Customer");

                    b.HasIndex("DateIn");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.TransactionCustomValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("Ticket");

                    b.HasIndex("Ticket", "CustomFieldId")
                        .IsUnique();

                    b.ToTable("TransactionCustomValues", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetainedTare")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RetainedTareUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("TruckId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseAtKiosk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("TruckId", "CarrierName")
                        .IsUnique();

                    b.ToTable("Trucks", (string)null);
                });

            modelBuilder.Entity("Foundation.Web.Models.CardCustomValue", b =>
                {
                    b.HasOne("Foundation.Web.Models.Card", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foundation.Web.Models.CustomField", null)
                        .WithMany()
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foundation.Web.Models.CustomFieldListValue", b =>
                {
                    b.HasOne("Foundation.Web.Models.CustomField", null)
                        .WithMany()
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foundation.Web.Models.LoadEmailLog", b =>
                {
                    b.HasOne("Foundation.Web.Models.LoadEmailRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Foundation.Web.Models.TransactionCustomValue", b =>
                {
                    b.HasOne("Foundation.Web.Models.CustomField", null)
                        .WithMany()
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foundation.Web.Models.Transaction", null)
                        .WithMany()
                        .HasForeignKey("Ticket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
